# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('item_status', models.CharField(choices=[('new', 'new'), ('done', 'done')], max_length=10)),
            ],
        ),
    ]
